import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@components/Navbar'
import { Providers } from '@redux/provider'

const poppins = Poppins({ subsets: ['latin'], weight: ['500'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={poppins.className}>
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  )
}
